# yaml-language-server: $schema=../bandex-config.schema.json
#
# Configurações do Bandex
bandex:
  # Configurações dos restaurantes:
  #
  # Aqui vamos definir quais e com quais cor os restaurantes serão exibidos.
  # A cor pode ser definida por RGB ou pelo nome da cor (os nomes das cores possíveis estão no schema
  # ou no enum Color em <https://docs.rs/colored/latest/colored/enum.Color.html#variants>)
  restaurants:
    # Restaurante da EACH
    - id: &RESTAURANT_EACH 13
      color: red

  # Configurações dos pratos:
  #
  # Aqui vamos definir quais pratos são gostados ou não gostados. Simplesmente
  # escreva uma lista de alimentos gostados (liked) e não gostados (disliked) -
  # se quiser, pode comidas gostadas e não gostadas em restaurantes específicos
  # (veja outros exemplos).
  foods:
    # Comidas gostadas
    # - brigadeiro e pudim
    liked:
      - brigadeiro
      - pudim

    # Comidas não gostadas
    # - acelga
    disliked:
      - acelga
