# yaml-language-server: $schema=../bandex-config.schema.json
#
# Configurações do Bandex
bandex:
  # Configurações dos restaurantes:
  #
  # Aqui vamos definir quais e com quais cor os restaurantes serão exibidos.
  # A cor pode ser definida por RGB ou pelo nome da cor (os nomes das cores possíveis estão no schema
  # ou no enum Color em <https://docs.rs/colored/latest/colored/enum.Color.html#variants>)
  restaurants:
    # Restaurante Física
    - id: &RESTAURANT_FISICA 8
      color: [240, 218, 94] # por RGB

    # Restaurante Química
    - id: &RESTAURANT_QUIMICA 9
      color: blue # por nome

    # Restaurante Prefeitura
    - id: &RESTAURANT_PREFEITURA 7
      # sem cor (o padrão é branco)

    # Restaurante Central
    - id: &RESTAURANT_CENTRAL 6
      color: yellow

  # Configurações dos pratos:
  #
  # Aqui vamos definir quais pratos são gostados ou não gostados. Simplesmente
  # escreva uma lista de alimentos gostados (liked) e não gostados (disliked) -
  # se quiser, pode comidas gostadas e não gostadas em restaurantes específicos.
  foods:
    # Comidas gostadas
    # - brigadeiro e pudim
    # - bananada e barra de cereais (só é gostada no central)
    liked:
      - brigadeiro
      - pudim
      - bananada: [*RESTAURANT_CENTRAL]
      # Também podemos escrever assim
      - barra de cereais:
          - *RESTAURANT_CENTRAL

    # Comidas não gostadas
    # - acelga
    # - pvt (só não é gostada no restaurante da física e da química)
    disliked:
      - pvt: [*RESTAURANT_FISICA, *RESTAURANT_QUIMICA]
      - acelga
