# yaml-language-server: $schema=../bandex-config.schema.json
#
# Configurações do Bandex
bandex:
  # Configurações dos restaurantes:
  #
  # Aqui vamos definir quais e com quais cor os restaurantes serão exibidos.
  # A cor pode ser definida por RGB ou pelo nome da cor (os nomes das cores possíveis estão no schema
  # ou no enum Color em <https://docs.rs/colored/latest/colored/enum.Color.html#variants>)
  restaurants:
    # Restaurante Física
    - id: &RESTAURANT_FISICA 8
      color: [240, 218, 94] # por RGB

    # Restaurante Química
    - id: &RESTAURANT_QUIMICA 9
      color: blue # por nome

    # Restaurante Prefeitura
    - id: &RESTAURANT_PREFEITURA 7
      # sem cor (o padrão é branco)

    # Restaurante Central
    - id: &RESTAURANT_CENTRAL 6
      color: yellow
